backend:
  name: github
  repo: themike900/BitcoinSranan-website
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Startpage"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Inhalt", name: "body", widget: "markdown" }

      - label: "Locals"
        name: "locals"
        file: "content/locals.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Inhalt", name: "body", widget: "markdown" }

      - label: "Internationals"
        name: "internationals"
        file: "content/internationals.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Inhalt", name: "body", widget: "markdown" }

      - label: "Community Hub"
        name: "community-hub"
        file: "content/community-hub.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Inhalt", name: "body", widget: "markdown" }

      - label: "BTCPay Server"
        name: "btcpayserver"
        file: "donations/btcpayserver.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Inhalt", name: "body", widget: "markdown" }
